@BASE_URL = http://localhost:3000

### GET - /
GET {{BASE_URL}}

### GET - /health
GET {{BASE_URL}}/health

### POST - /auth/register
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@ex.com",
    "password": "password"
}

### POST - /auth/login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "johndoe@ex.com",
    "password": "password"
}

### POST - /auth/logout
POST {{BASE_URL}}/auth/logout

### POST - /auth/refresh
POST {{BASE_URL}}/auth/refresh

### GET - /users/me
GET {{BASE_URL}}/users/me

### POST - /buckets
POST {{BASE_URL}}/buckets
Content-Type: application/json

{
    "name": "OpenAPI",
    "pricePerRequest": 12
}

### GET - /buckets
GET {{BASE_URL}}/buckets

### GET - /buckets/:id
GET {{BASE_URL}}/buckets/9901f67f-2ac4-48b7-8e65-32165f1b5e51

### PATCH - /buckets/:id
PATCH {{BASE_URL}}/buckets/9901f67f-2ac4-48b7-8e65-32165f1b5e51
Content-Type: application/json

{
 "name": "OpenAPI"
}

### DELETE - /buckets/:id
DELETE {{BASE_URL}}/buckets/9901f67f-2ac4-48b7-8e65-32165f1b5e51